### PR TITLE
Upgrade Nginx, PageSpeed and Ubuntu versions

### PR DESCRIPTION
**Pull request by bigfoot90**
Compile on `Ubuntu 16.04 LTS` with `nginx-v1.14.0` and `PageSpeed-1.13.35.2-stable`

### CODE REVIEW

**Comment by bigfoot90** [comment]
CI is failing `No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)`
but there is any `rakefile` file from master

**Comment by elct9620** [comment]
This is travis-ci auto enable all CI for my repository after I re-link it, I will disable it.

**Comment by bigfoot90** [comment]
Thanks for your quick merge of this PR.
Can you tag this version for Docker Hub?

**Comment by elct9620** [comment]
Yes, I will add a new tag for this version.

**Pull request merged**
